# Generated by Django 4.1 on 2024-12-26 22:20

import django.contrib.auth.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('register', '0013_alter_customuser_state'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='postal_cd',
            field=models.CharField(blank=True, max_length=7, validators=[django.core.validators.RegexValidator(message='郵便番号は7桁の数字で入力してください', regex='^[0-9]+$')], verbose_name='郵便番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='tel_number',
            field=models.CharField(blank=True, max_length=15, validators=[django.core.validators.RegexValidator(message='電話番号は15桁までの数字で入力してください', regex='^[0-9]+$')], verbose_name='電話番号'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='username',
            field=models.CharField(error_messages={'unique': 'このユーザー名は既に使用されています。'}, max_length=50, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='ユーザー名'),
        ),
    ]
